export const GET_MOVIES = 'GET_MOVIES'
export const LIKE_MOVIE = 'LIKE_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'

export const UPDATE_COLUMN_SELECTED = 'UPDATE_COLUMN_SELECTED'
export const UPDATE_SORT_ORDER = 'UPDATE_SORT_ORDER'

export const GET_GENRES = 'GET_GENRES'
export const UPDATE_CURRENT_GENRE='UPDATE_CURRENT_GENRE'

export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE'

export const UPDATE_LOGIN = 'UPDATE_LOGIN'
export const LOGIN_ERRORS = 'LOGIN_ERRORS'
export const UPDATE_DETAILS = 'UPDATE_DETAILS'
export const INPUT_FIELD_ERROR = 'INPUT_FIELD_ERROR'